project_id = "lrxdllwaiakbgayrzgws"

[functions.analyze-trash]
verify_jwt = false

[functions.ecoza-chat]
verify_jwt = false

[functions.environment-data]
verify_jwt = false

[functions.disposal-machines]
verify_jwt = false